name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: side-assist-desktop
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: side-assist-desktop.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: side-assist-desktop
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: side-assist-desktop

    steps:
    - uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: side-assist-desktop/package-lock.json

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './side-assist-desktop/src-tauri -> target'

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev librsvg2-dev

    - name: Install dependencies
      run: npm ci
      working-directory: side-assist-desktop

    - name: Build Tauri app
      run: npm run tauri build -- --target ${{ matrix.target }}
      working-directory: side-assist-desktop

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: side-assist-desktop/src-tauri/target/${{ matrix.target }}/release/bundle/**/*
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
        prerelease: false